# coding: utf-8

"""
    Hardware Wallet Daemon API

    This is the hardware-wallet-daemon API  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: steve@skycoin.net
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class GenerateAddressesRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'address_n': 'int',
        'start_index': 'int',
        'confirm_address': 'bool'
    }

    attribute_map = {
        'address_n': 'address_n',
        'start_index': 'start_index',
        'confirm_address': 'confirm_address'
    }

    def __init__(self, address_n=None, start_index=None, confirm_address=None):  # noqa: E501
        """GenerateAddressesRequest - a model defined in OpenAPI"""  # noqa: E501

        self._address_n = None
        self._start_index = None
        self._confirm_address = None
        self.discriminator = None

        self.address_n = address_n
        if start_index is not None:
            self.start_index = start_index
        if confirm_address is not None:
            self.confirm_address = confirm_address

    @property
    def address_n(self):
        """Gets the address_n of this GenerateAddressesRequest.  # noqa: E501


        :return: The address_n of this GenerateAddressesRequest.  # noqa: E501
        :rtype: int
        """
        return self._address_n

    @address_n.setter
    def address_n(self, address_n):
        """Sets the address_n of this GenerateAddressesRequest.


        :param address_n: The address_n of this GenerateAddressesRequest.  # noqa: E501
        :type: int
        """
        if address_n is None:
            raise ValueError("Invalid value for `address_n`, must not be `None`")  # noqa: E501

        self._address_n = address_n

    @property
    def start_index(self):
        """Gets the start_index of this GenerateAddressesRequest.  # noqa: E501


        :return: The start_index of this GenerateAddressesRequest.  # noqa: E501
        :rtype: int
        """
        return self._start_index

    @start_index.setter
    def start_index(self, start_index):
        """Sets the start_index of this GenerateAddressesRequest.


        :param start_index: The start_index of this GenerateAddressesRequest.  # noqa: E501
        :type: int
        """

        self._start_index = start_index

    @property
    def confirm_address(self):
        """Gets the confirm_address of this GenerateAddressesRequest.  # noqa: E501


        :return: The confirm_address of this GenerateAddressesRequest.  # noqa: E501
        :rtype: bool
        """
        return self._confirm_address

    @confirm_address.setter
    def confirm_address(self, confirm_address):
        """Sets the confirm_address of this GenerateAddressesRequest.


        :param confirm_address: The confirm_address of this GenerateAddressesRequest.  # noqa: E501
        :type: bool
        """

        self._confirm_address = confirm_address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GenerateAddressesRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
