# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.25.1
    Contact: contact@skycoin.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import skyapi
from skyapi.models.inline_response2007_data import InlineResponse2007Data  # noqa: E501
from skyapi.rest import ApiException


class TestInlineResponse2007Data(unittest.TestCase):
    """InlineResponse2007Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2007Data(self):
        """Test InlineResponse2007Data"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyapi.models.inline_response2007_data.InlineResponse2007Data()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
