# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.25.1
    Contact: contact@skycoin.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import skyapi
from skyapi.models.apiv1wallettransaction_wallet import Apiv1wallettransactionWallet  # noqa: E501
from skyapi.rest import ApiException


class TestApiv1wallettransactionWallet(unittest.TestCase):
    """Apiv1wallettransactionWallet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiv1wallettransactionWallet(self):
        """Test Apiv1wallettransactionWallet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyapi.models.apiv1wallettransaction_wallet.Apiv1wallettransactionWallet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
