# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.25.1
    Contact: skycoin.doe@example.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.apiv1wallets_entries import Apiv1walletsEntries  # noqa: E501
from openapi_client.rest import ApiException


class TestApiv1walletsEntries(unittest.TestCase):
    """Apiv1walletsEntries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiv1walletsEntries(self):
        """Test Apiv1walletsEntries"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.apiv1wallets_entries.Apiv1walletsEntries()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
