# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@skycoin.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.build_info import BuildInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestBuildInfo(unittest.TestCase):
    """BuildInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBuildInfo(self):
        """Test BuildInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.build_info.BuildInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
