# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@skycoin.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_coin_supply(self):
        """Test case for coin_supply

        """
        pass

    def test_csrf_token(self):
        """Test case for csrf_token

        Creates a new CSRF token. Previous CSRF tokens are invalidated by this call.  # noqa: E501
        """
        pass

    def test_resend_unconfirmed_txns(self):
        """Test case for resend_unconfirmed_txns

        """
        pass

    def test_version(self):
        """Test case for version

        """
        pass

    def test_wallet_folder(self):
        """Test case for wallet_folder

        """
        pass


if __name__ == '__main__':
    unittest.main()
