# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    The version of the OpenAPI document: 0.27.0
    Contact: contact@skycoin.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import skyapi
from skyapi.models.transaction_status import TransactionStatus  # noqa: E501
from skyapi.rest import ApiException


class TestTransactionStatus(unittest.TestCase):
    """TransactionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionStatus(self):
        """Test TransactionStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyapi.models.transaction_status.TransactionStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
