%apply int* OUTPUT {GoInt*} 
%apply int* OUTPUT {GoUint8*} 
%apply int* OUTPUT {GoInt8*} 
%apply int* OUTPUT {GoUint16*} 
%apply int* OUTPUT {GoInt16*} 
%apply int* OUTPUT {GoUint32*} 
%apply int* OUTPUT {GoInt32*} 
%apply int* OUTPUT {GoUint64*} 
%apply int* OUTPUT {GoInt64*} 
