# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.26.0
    Contact: contact@skycoin.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import skyapi
from skyapi.models.transaction_v2_params_unspent_to import TransactionV2ParamsUnspentTo  # noqa: E501
from skyapi.rest import ApiException


class TestTransactionV2ParamsUnspentTo(unittest.TestCase):
    """TransactionV2ParamsUnspentTo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionV2ParamsUnspentTo(self):
        """Test TransactionV2ParamsUnspentTo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyapi.models.transaction_v2_params_unspent_to.TransactionV2ParamsUnspentTo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
