# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.26.0
    Contact: contact@skycoin.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import skyapi
from skyapi.models.api_v1_pending_txs_transaction_outputs import ApiV1PendingTxsTransactionOutputs  # noqa: E501
from skyapi.rest import ApiException


class TestApiV1PendingTxsTransactionOutputs(unittest.TestCase):
    """ApiV1PendingTxsTransactionOutputs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV1PendingTxsTransactionOutputs(self):
        """Test ApiV1PendingTxsTransactionOutputs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyapi.models.api_v1_pending_txs_transaction_outputs.ApiV1PendingTxsTransactionOutputs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
