# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.25.1
    Contact: contact@skycoin.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import skyapi
from skyapi.models.api_v1_wallets_entries import ApiV1WalletsEntries  # noqa: E501
from skyapi.rest import ApiException


class TestApiV1WalletsEntries(unittest.TestCase):
    """ApiV1WalletsEntries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV1WalletsEntries(self):
        """Test ApiV1WalletsEntries"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyapi.models.api_v1_wallets_entries.ApiV1WalletsEntries()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
