# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.26.0
    Contact: contact@skycoin.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import skyapi
from skyapi.models.transaction_v2_params_address import TransactionV2ParamsAddress  # noqa: E501
from skyapi.rest import ApiException


class TestTransactionV2ParamsAddress(unittest.TestCase):
    """TransactionV2ParamsAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionV2ParamsAddress(self):
        """Test TransactionV2ParamsAddress"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyapi.models.transaction_v2_params_address.TransactionV2ParamsAddress()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
