# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.25.1
    Contact: contact@skycoin.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import skyapi
from skyapi.models.apiv1pending_txs_transaction import Apiv1pendingTxsTransaction  # noqa: E501
from skyapi.rest import ApiException


class TestApiv1pendingTxsTransaction(unittest.TestCase):
    """Apiv1pendingTxsTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiv1pendingTxsTransaction(self):
        """Test Apiv1pendingTxsTransaction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyapi.models.apiv1pending_txs_transaction.Apiv1pendingTxsTransaction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
