# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.25.1
    Contact: contact@skycoin.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import skyapi
from skyapi.models.apiv1exploreraddress_status import Apiv1exploreraddressStatus  # noqa: E501
from skyapi.rest import ApiException


class TestApiv1exploreraddressStatus(unittest.TestCase):
    """Apiv1exploreraddressStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiv1exploreraddressStatus(self):
        """Test Apiv1exploreraddressStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyapi.models.apiv1exploreraddress_status.Apiv1exploreraddressStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
