# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.25.1
    Contact: contact@skycoin.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import skyapi
from skyapi.models.api_v1_wallet_transaction_wallet import ApiV1WalletTransactionWallet  # noqa: E501
from skyapi.rest import ApiException


class TestApiV1WalletTransactionWallet(unittest.TestCase):
    """ApiV1WalletTransactionWallet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV1WalletTransactionWallet(self):
        """Test ApiV1WalletTransactionWallet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyapi.models.api_v1_wallet_transaction_wallet.ApiV1WalletTransactionWallet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
