# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.26.0
    Contact: contact@skycoin.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import skyapi
from skyapi.models.inline_response2008_data import InlineResponse2008Data  # noqa: E501
from skyapi.rest import ApiException


class TestInlineResponse2008Data(unittest.TestCase):
    """InlineResponse2008Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2008Data(self):
        """Test InlineResponse2008Data"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyapi.models.inline_response2008_data.InlineResponse2008Data()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
