# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.25.1
    Contact: contact@skycoin.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import skyapi
from skyapi.models.apiv1exploreraddress_outputs import Apiv1exploreraddressOutputs  # noqa: E501
from skyapi.rest import ApiException


class TestApiv1exploreraddressOutputs(unittest.TestCase):
    """Apiv1exploreraddressOutputs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiv1exploreraddressOutputs(self):
        """Test Apiv1exploreraddressOutputs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyapi.models.apiv1exploreraddress_outputs.Apiv1exploreraddressOutputs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
