# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.26.0
    Contact: contact@skycoin.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import skyapi
from skyapi.models.wallet_transaction_sign_request import WalletTransactionSignRequest  # noqa: E501
from skyapi.rest import ApiException


class TestWalletTransactionSignRequest(unittest.TestCase):
    """WalletTransactionSignRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWalletTransactionSignRequest(self):
        """Test WalletTransactionSignRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyapi.models.wallet_transaction_sign_request.WalletTransactionSignRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
