# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.25.1
    Contact: contact@skycoin.net
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ApiV1WalletTransactionTo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'hours': 'int',
        'address': 'str',
        'coins': 'int'
    }

    attribute_map = {
        'hours': 'hours',
        'address': 'address',
        'coins': 'coins'
    }

    def __init__(self, hours=None, address=None, coins=None):  # noqa: E501
        """ApiV1WalletTransactionTo - a model defined in OpenAPI"""  # noqa: E501

        self._hours = None
        self._address = None
        self._coins = None
        self.discriminator = None

        if hours is not None:
            self.hours = hours
        if address is not None:
            self.address = address
        if coins is not None:
            self.coins = coins

    @property
    def hours(self):
        """Gets the hours of this ApiV1WalletTransactionTo.  # noqa: E501


        :return: The hours of this ApiV1WalletTransactionTo.  # noqa: E501
        :rtype: int
        """
        return self._hours

    @hours.setter
    def hours(self, hours):
        """Sets the hours of this ApiV1WalletTransactionTo.


        :param hours: The hours of this ApiV1WalletTransactionTo.  # noqa: E501
        :type: int
        """

        self._hours = hours

    @property
    def address(self):
        """Gets the address of this ApiV1WalletTransactionTo.  # noqa: E501


        :return: The address of this ApiV1WalletTransactionTo.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this ApiV1WalletTransactionTo.


        :param address: The address of this ApiV1WalletTransactionTo.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def coins(self):
        """Gets the coins of this ApiV1WalletTransactionTo.  # noqa: E501


        :return: The coins of this ApiV1WalletTransactionTo.  # noqa: E501
        :rtype: int
        """
        return self._coins

    @coins.setter
    def coins(self, coins):
        """Sets the coins of this ApiV1WalletTransactionTo.


        :param coins: The coins of this ApiV1WalletTransactionTo.  # noqa: E501
        :type: int
        """

        self._coins = coins

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiV1WalletTransactionTo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
