# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.26.0
    Contact: contact@skycoin.net
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class BlockVerboseSchemaHeader(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'seq': 'int',
        'timestamp': 'int',
        'fee': 'int',
        'version': 'int',
        'block_hash': 'str',
        'previous_block_hash': 'str',
        'tx_body_hash': 'str',
        'ux_hash': 'str'
    }

    attribute_map = {
        'seq': 'seq',
        'timestamp': 'timestamp',
        'fee': 'fee',
        'version': 'version',
        'block_hash': 'block_hash',
        'previous_block_hash': 'previous_block_hash',
        'tx_body_hash': 'tx_body_hash',
        'ux_hash': 'ux_hash'
    }

    def __init__(self, seq=None, timestamp=None, fee=None, version=None, block_hash=None, previous_block_hash=None, tx_body_hash=None, ux_hash=None):  # noqa: E501
        """BlockVerboseSchemaHeader - a model defined in OpenAPI"""  # noqa: E501

        self._seq = None
        self._timestamp = None
        self._fee = None
        self._version = None
        self._block_hash = None
        self._previous_block_hash = None
        self._tx_body_hash = None
        self._ux_hash = None
        self.discriminator = None

        if seq is not None:
            self.seq = seq
        if timestamp is not None:
            self.timestamp = timestamp
        if fee is not None:
            self.fee = fee
        if version is not None:
            self.version = version
        if block_hash is not None:
            self.block_hash = block_hash
        if previous_block_hash is not None:
            self.previous_block_hash = previous_block_hash
        if tx_body_hash is not None:
            self.tx_body_hash = tx_body_hash
        if ux_hash is not None:
            self.ux_hash = ux_hash

    @property
    def seq(self):
        """Gets the seq of this BlockVerboseSchemaHeader.  # noqa: E501


        :return: The seq of this BlockVerboseSchemaHeader.  # noqa: E501
        :rtype: int
        """
        return self._seq

    @seq.setter
    def seq(self, seq):
        """Sets the seq of this BlockVerboseSchemaHeader.


        :param seq: The seq of this BlockVerboseSchemaHeader.  # noqa: E501
        :type: int
        """

        self._seq = seq

    @property
    def timestamp(self):
        """Gets the timestamp of this BlockVerboseSchemaHeader.  # noqa: E501


        :return: The timestamp of this BlockVerboseSchemaHeader.  # noqa: E501
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this BlockVerboseSchemaHeader.


        :param timestamp: The timestamp of this BlockVerboseSchemaHeader.  # noqa: E501
        :type: int
        """

        self._timestamp = timestamp

    @property
    def fee(self):
        """Gets the fee of this BlockVerboseSchemaHeader.  # noqa: E501


        :return: The fee of this BlockVerboseSchemaHeader.  # noqa: E501
        :rtype: int
        """
        return self._fee

    @fee.setter
    def fee(self, fee):
        """Sets the fee of this BlockVerboseSchemaHeader.


        :param fee: The fee of this BlockVerboseSchemaHeader.  # noqa: E501
        :type: int
        """

        self._fee = fee

    @property
    def version(self):
        """Gets the version of this BlockVerboseSchemaHeader.  # noqa: E501


        :return: The version of this BlockVerboseSchemaHeader.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this BlockVerboseSchemaHeader.


        :param version: The version of this BlockVerboseSchemaHeader.  # noqa: E501
        :type: int
        """

        self._version = version

    @property
    def block_hash(self):
        """Gets the block_hash of this BlockVerboseSchemaHeader.  # noqa: E501


        :return: The block_hash of this BlockVerboseSchemaHeader.  # noqa: E501
        :rtype: str
        """
        return self._block_hash

    @block_hash.setter
    def block_hash(self, block_hash):
        """Sets the block_hash of this BlockVerboseSchemaHeader.


        :param block_hash: The block_hash of this BlockVerboseSchemaHeader.  # noqa: E501
        :type: str
        """

        self._block_hash = block_hash

    @property
    def previous_block_hash(self):
        """Gets the previous_block_hash of this BlockVerboseSchemaHeader.  # noqa: E501


        :return: The previous_block_hash of this BlockVerboseSchemaHeader.  # noqa: E501
        :rtype: str
        """
        return self._previous_block_hash

    @previous_block_hash.setter
    def previous_block_hash(self, previous_block_hash):
        """Sets the previous_block_hash of this BlockVerboseSchemaHeader.


        :param previous_block_hash: The previous_block_hash of this BlockVerboseSchemaHeader.  # noqa: E501
        :type: str
        """

        self._previous_block_hash = previous_block_hash

    @property
    def tx_body_hash(self):
        """Gets the tx_body_hash of this BlockVerboseSchemaHeader.  # noqa: E501


        :return: The tx_body_hash of this BlockVerboseSchemaHeader.  # noqa: E501
        :rtype: str
        """
        return self._tx_body_hash

    @tx_body_hash.setter
    def tx_body_hash(self, tx_body_hash):
        """Sets the tx_body_hash of this BlockVerboseSchemaHeader.


        :param tx_body_hash: The tx_body_hash of this BlockVerboseSchemaHeader.  # noqa: E501
        :type: str
        """

        self._tx_body_hash = tx_body_hash

    @property
    def ux_hash(self):
        """Gets the ux_hash of this BlockVerboseSchemaHeader.  # noqa: E501


        :return: The ux_hash of this BlockVerboseSchemaHeader.  # noqa: E501
        :rtype: str
        """
        return self._ux_hash

    @ux_hash.setter
    def ux_hash(self, ux_hash):
        """Sets the ux_hash of this BlockVerboseSchemaHeader.


        :param ux_hash: The ux_hash of this BlockVerboseSchemaHeader.  # noqa: E501
        :type: str
        """

        self._ux_hash = ux_hash

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BlockVerboseSchemaHeader):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
