# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.25.1
    Contact: contact@skycoin.net
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse2005(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'entries': 'list[ApiV1WalletsEntries]',
        'meta': 'ApiV1WalletsMeta'
    }

    attribute_map = {
        'entries': 'entries',
        'meta': 'meta'
    }

    def __init__(self, entries=None, meta=None):  # noqa: E501
        """InlineResponse2005 - a model defined in OpenAPI"""  # noqa: E501

        self._entries = None
        self._meta = None
        self.discriminator = None

        if entries is not None:
            self.entries = entries
        if meta is not None:
            self.meta = meta

    @property
    def entries(self):
        """Gets the entries of this InlineResponse2005.  # noqa: E501


        :return: The entries of this InlineResponse2005.  # noqa: E501
        :rtype: list[ApiV1WalletsEntries]
        """
        return self._entries

    @entries.setter
    def entries(self, entries):
        """Sets the entries of this InlineResponse2005.


        :param entries: The entries of this InlineResponse2005.  # noqa: E501
        :type: list[ApiV1WalletsEntries]
        """

        self._entries = entries

    @property
    def meta(self):
        """Gets the meta of this InlineResponse2005.  # noqa: E501


        :return: The meta of this InlineResponse2005.  # noqa: E501
        :rtype: ApiV1WalletsMeta
        """
        return self._meta

    @meta.setter
    def meta(self, meta):
        """Sets the meta of this InlineResponse2005.


        :param meta: The meta of this InlineResponse2005.  # noqa: E501
        :type: ApiV1WalletsMeta
        """

        self._meta = meta

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2005):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
