# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.26.0
    Contact: contact@skycoin.net
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class TransactionV2ParamsAddress(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'hours_selection': 'TransactionV2ParamsAddressHoursSelection'
    }

    attribute_map = {
        'hours_selection': 'hours_selection'
    }

    def __init__(self, hours_selection=None):  # noqa: E501
        """TransactionV2ParamsAddress - a model defined in OpenAPI"""  # noqa: E501

        self._hours_selection = None
        self.discriminator = None

        if hours_selection is not None:
            self.hours_selection = hours_selection

    @property
    def hours_selection(self):
        """Gets the hours_selection of this TransactionV2ParamsAddress.  # noqa: E501


        :return: The hours_selection of this TransactionV2ParamsAddress.  # noqa: E501
        :rtype: TransactionV2ParamsAddressHoursSelection
        """
        return self._hours_selection

    @hours_selection.setter
    def hours_selection(self, hours_selection):
        """Sets the hours_selection of this TransactionV2ParamsAddress.


        :param hours_selection: The hours_selection of this TransactionV2ParamsAddress.  # noqa: E501
        :type: TransactionV2ParamsAddressHoursSelection
        """

        self._hours_selection = hours_selection

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransactionV2ParamsAddress):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
