# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.26.0
    Contact: contact@skycoin.net
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class WalletTransactionSignRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'wallet_id': 'str',
        'password': 'str',
        'encoded_transaction': 'str',
        'sign_indexes': 'list[int]'
    }

    attribute_map = {
        'wallet_id': 'wallet_id',
        'password': 'password',
        'encoded_transaction': 'encoded_transaction',
        'sign_indexes': 'sign_indexes'
    }

    def __init__(self, wallet_id=None, password=None, encoded_transaction=None, sign_indexes=None):  # noqa: E501
        """WalletTransactionSignRequest - a model defined in OpenAPI"""  # noqa: E501

        self._wallet_id = None
        self._password = None
        self._encoded_transaction = None
        self._sign_indexes = None
        self.discriminator = None

        if wallet_id is not None:
            self.wallet_id = wallet_id
        if password is not None:
            self.password = password
        if encoded_transaction is not None:
            self.encoded_transaction = encoded_transaction
        if sign_indexes is not None:
            self.sign_indexes = sign_indexes

    @property
    def wallet_id(self):
        """Gets the wallet_id of this WalletTransactionSignRequest.  # noqa: E501


        :return: The wallet_id of this WalletTransactionSignRequest.  # noqa: E501
        :rtype: str
        """
        return self._wallet_id

    @wallet_id.setter
    def wallet_id(self, wallet_id):
        """Sets the wallet_id of this WalletTransactionSignRequest.


        :param wallet_id: The wallet_id of this WalletTransactionSignRequest.  # noqa: E501
        :type: str
        """

        self._wallet_id = wallet_id

    @property
    def password(self):
        """Gets the password of this WalletTransactionSignRequest.  # noqa: E501


        :return: The password of this WalletTransactionSignRequest.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this WalletTransactionSignRequest.


        :param password: The password of this WalletTransactionSignRequest.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def encoded_transaction(self):
        """Gets the encoded_transaction of this WalletTransactionSignRequest.  # noqa: E501


        :return: The encoded_transaction of this WalletTransactionSignRequest.  # noqa: E501
        :rtype: str
        """
        return self._encoded_transaction

    @encoded_transaction.setter
    def encoded_transaction(self, encoded_transaction):
        """Sets the encoded_transaction of this WalletTransactionSignRequest.


        :param encoded_transaction: The encoded_transaction of this WalletTransactionSignRequest.  # noqa: E501
        :type: str
        """

        self._encoded_transaction = encoded_transaction

    @property
    def sign_indexes(self):
        """Gets the sign_indexes of this WalletTransactionSignRequest.  # noqa: E501


        :return: The sign_indexes of this WalletTransactionSignRequest.  # noqa: E501
        :rtype: list[int]
        """
        return self._sign_indexes

    @sign_indexes.setter
    def sign_indexes(self, sign_indexes):
        """Sets the sign_indexes of this WalletTransactionSignRequest.


        :param sign_indexes: The sign_indexes of this WalletTransactionSignRequest.  # noqa: E501
        :type: list[int]
        """

        self._sign_indexes = sign_indexes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WalletTransactionSignRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
