# coding: utf-8

"""
    Hardware Wallet Daemon API

    This is the hardware-wallet-daemon API  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: steve@skycoin.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import skyhwd
from skyhwd.models.word_request import WordRequest  # noqa: E501
from skyhwd.rest import ApiException


class TestWordRequest(unittest.TestCase):
    """WordRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWordRequest(self):
        """Test WordRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyhwd.models.word_request.WordRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
