# coding: utf-8

"""
    Hardware Wallet Daemon API

    This is the hardware-wallet-daemon API  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: steve@skycoin.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import skyhwd
from skyhwd.models.http_error_response_error import HTTPErrorResponseError  # noqa: E501
from skyhwd.rest import ApiException


class TestHTTPErrorResponseError(unittest.TestCase):
    """HTTPErrorResponseError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHTTPErrorResponseError(self):
        """Test HTTPErrorResponseError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyhwd.models.http_error_response_error.HTTPErrorResponseError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
